version: "3.8"

services:
  jaegerService:
    image: jaegertracing/all-in-one:1.29
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgress:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Orders"
    ports:
      - "5432:5432"     
  payservice:
    image: org/payservice
    ports:
     - 9089:9089
    environment:
      JAEGER_HOST: jaegerService        
  ordergenerator:
    image: org/generatorservice
    ports:
      - 9081:9081
    environment:
      JAEGER_HOST: jaegerService     
  orderpersistence:
    image: org/persistenceservice
    ports:
      - 9087:9087
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgress:5432/Orders
      KAFKA_SERVER: kafka:9092
      PAY_SERVICE: http://payservice:9089  
      JAEGER_HOST: jaegerService
  analyticservice:
    image: org/analyticservice
    ports:
      - 9086:9086
    environment:
      KAFKA_SERVER: kafka:9092
      JAEGER_HOST: jaegerService  
  senderService:
    image: org/senderservice
    ports:
      - 8099:8099
    environment:
      ORDER_SERVER: http://ordergenerator:9081/order
      KAFKA_SERVER: kafka:9092
      JAEGER_HOST: jaegerService        
       
